### ISSUE TITLE
Verify captcha...

### ISSUE THREAD

**Issue by chaoscreater** [luckyjoker993/epic_games_free_games_claim#1]
Hi there,

Thanks for making this! I've tested your script andd it works great. However, there is a small issue. Sometimes when it gets to the purchasing order stage, it will prompt you to verify captcha. Before you could verify the captcha, the script will load the page for the next free game. It will just keep prompting you to verify captcha and the order will never be purchased, because the script doesn't wait for the captcha to be verified. It's quite weird, because you are already logged in and it still prompts for captcha.

I have 5 Epic Games accounts and if I use your script to run through each account, it will very easily prompt for captcha even when you're already logged in.

**Comment by ghost** [comment]
just rewrote the script. now it checks if there is a captcha. try it and let me know if it works. added support for multiaccounts.

**Comment by chaoscreater** [comment]
It works! Legend!

BTW, the new script doesn't seem to save session anymore? I think it just does a new login session for each account when it runs?

**Comment by ghost** [comment]
Just open settings.py and change save cookies to True. I set it to False by default because if you run the script once a week it doesn't save the session for that long and asks to login anyway.
